### ISSUE TITLE
边的信息

### ISSUE THREAD

**Issue by h161020716** [Zhu-Shatong/DynamicSocialNetworkFraudDetection#2]
”从节点 A 指向节点 B 的有向边代表用户 A 将用户 B 填为他的紧急联系人“，pdf中的这句话，边的信息是什么，什么叫做紧急联系人，在现实企业间似乎没有紧急联系人这一概念

**Comment by Zhu-Shatong** [comment]
你好！这个的背景是“第七届信也科技杯-欺诈用户风险识别”的比赛数据集（略微改动），你可以查看一下数据集说明的网址：https://ai.ppdai.com/mirror/goToMirrorDetailSix?mirrorId=28&tabindex=1  

edge_type:
边类型，shape为(N_edge,)，代表了不同分类的紧急联系人。（我当时写的时候也没有深究这里面的含义，pdf是含有自己的浅薄理解，也有aigc的成分，数据集说明的全部解释以网站为准，同时网站也有很多优秀作品的ppt可以参考~）

感谢！
